# Generated by Django 5.1.6 on 2025-02-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('resultado', models.JSONField(default=dict)),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
